server {
    listen 80;
    server_name your-domain.com www.your-domain.com;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /var/www/easybuy/staticfiles/;
    }

    location /media/ {
        alias /var/www/easybuy/easybuy/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/easybuy/easybuy.sock;
    }
}