# Generated by Django 5.2.7 on 2026-04-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ad_models_and_add_banner_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='core_banner_is_acti_4fdaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['start_date', 'end_date'], name='core_banner_start_d_bb0bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='core_catego_is_acti_26a709_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'is_active'], name='core_subcat_categor_b66c44_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['is_active'], name='core_subcat_is_acti_007df6_idx'),
        ),
    ]
