# Generated by Django 6.0.2 on 2026-04-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_add_product_rejection_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'id']},
        ),
    ]
