# Generated by Django 6.0.2 on 2026-03-23 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_orderitem_estimated_ship_date_orderitem_shipped_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order_updates', models.BooleanField(default=True, verbose_name='Email Order Updates')),
                ('whatsapp_order_updates', models.BooleanField(default=True, verbose_name='WhatsApp Order Updates')),
                ('email_promotions', models.BooleanField(default=True, verbose_name='Email Promotions')),
                ('whatsapp_promotions', models.BooleanField(default=False, verbose_name='WhatsApp Promotions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
