# Generated by Django 6.0.2 on 2026-03-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_sellerprofile_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
