# Generated by Django 6.0.2 on 2026-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_savedcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
