# Generated by Django 5.2.7 on 2026-04-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_returnrequestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment'), ('COD', 'Cash on Delivery')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
